name: Continuous delivery

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Continuous integration
    runs-on: ubuntu-latest

    steps:
      - name: "Init repository"
        uses: actions/checkout@v3

      - name: "Install node"
        uses: actions/setup-node@v3
        with:
          node-version: '19'

      - name: "Install JS dependencies"
        run: npm install

      - name: "Run eslint"
        run: npx eslint index.js

      - name: "Run jest"
        run: npm run test

      - uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}